development:
    default_user: 2
    admin_user: 1
    moving_average_window: 5
    lowest_sample_rate: 40
    google_maps_api_key: "ABQIAAAAI7vgMWXyJttIg3zaex8VQBS8AnXYoE8C-F64DtdDJq8UsxjJ0hRgLHNjEsGnhPbSknXTWgAOGMt14g"
    
staging:
    default_user: 2
    admin_user: 1
    moving_average_window: 5
    lowest_sample_rate: 40
    google_maps_api_key: "ABQIAAAAnVqhbArFwBqhx-mW3fcEshTg1iE0bNP3B3hFkhFZrB9MzkeRtBRdVCZ0d9k3z3fk7kumVf0Nr-STiQ"
    
production:
    default_user: 2
    admin_user: 1
    moving_average_window: 5
    lowest_sample_rate: 40
    google_maps_api_key: "ABQIAAAAnVqhbArFwBqhx-mW3fcEshTETz3d-fMK8kp7L9EbuRfE46x2OxTqDouc8lgmTyRFScqhwIFyKBW6mA"